[package]
name = "discount-function"
version = "1.0.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.226", features = ["derive"] }
serde_json = "1.0.145"
shopify_function = "1.1.0"

[profile.release]
lto = true
opt-level = "z"
strip = true
